[package]
name = "n2t_jack"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
n2t_asm = { path = "../n2t_asm" }
strum = "0.24.0"
strum_macros = "0.24.0"

