use crate::assemble::symbol_table::Address;

pub const SYMBOLS: &[(&'static str, Address)] = &[
    ("R0", Address::Ram(0)),
    ("R1", Address::Ram(1)),
    ("R2", Address::Ram(2)),
    ("R3", Address::Ram(3)),
    ("R4", Address::Ram(4)),
    ("R5", Address::Ram(5)),
    ("R6", Address::Ram(6)),
    ("R7", Address::Ram(7)),
    ("R8", Address::Ram(8)),
    ("R9", Address::Ram(9)),
    ("R10", Address::Ram(10)),
    ("R11", Address::Ram(11)),
    ("R12", Address::Ram(12)),
    ("R13", Address::Ram(13)),
    ("R14", Address::Ram(14)),
    ("R15", Address::Ram(15)),
    ("SP", Address::Ram(0)),
    ("LCL", Address::Ram(1)),
    ("ARG", Address::Ram(2)),
    ("THIS", Address::Ram(3)),
    ("THAT", Address::Ram(4)),
    ("SCREEN", Address::Ram(0x4000)),
    ("KBD", Address::Ram(0x6000)),
];
